mdk-devel-backup from 2019-06-27 23:33

diff --git a/mdk/m23helper/compressedDebootstrap b/mdk/m23helper/compressedDebootstrap
--- a/mdk/m23helper/compressedDebootstrap
+++ b/mdk/m23helper/compressedDebootstrap
@@ -19,11 +19,25 @@ else
 	arch=`dpkg-architecture | grep DEB_HOST_ARCH= | cut -d'=' -f2`
 fi
 
+out="$suite-$arch.tar.7z"
+
 mkdir "$suite-$arch"
 cd "$suite-$arch"
 
+debootstrapBin="$(whereis debootstrap | awk '{print $2}')"
+
+if [ ! -f "$debootstrapBin" ]
+then
+	echo "ERROR: debootstrap could NOT befound!"
+	exit 1
+fi
+
+mv /usr/bin/arch-test /usr/bin/arch-test.raus
+
 #Debootstrap the distribution
-debootstrap --arch=$arch --include="parted wget net-tools" $suite . http://ftp.de.debian.org/debian
+"$debootstrapBin" --arch=$arch --include="parted wget net-tools gnupg" $suite . http://ftp.de.debian.org/debian
+
+mv /usr/bin/arch-test.raus /usr/bin/arch-test
 
 #Delete the packages
 rm ./var/cache/apt/archives/* 2> /dev/null
@@ -32,7 +46,22 @@ rm ./var/cache/apt/archives/* 2> /dev/null
 rm ./var/lib/apt/lists/* 2> /dev/null
 
 #Compress the debootstrapped dir
-tar -c --same-owner . | 7za a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -si ../"$suite-$arch.tar.7z"
-
+tar -cf - --same-owner . | 7za a -si ../"$out"
+#old parameters: tar -cf - --same-owner . | 7za a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -si ../"$suite-$arch.tar.7z"
 cd ..
+
+
+# Test the compressed tar.7z by extracting it
+mkdir test
+cd test
+7zr x -so ../"$out" | tar xp --same-owner
+if [ $? -ne 0 ]
+then
+	echo "ERROR: Testing tar.7z failed!"
+	exit 1
+fi
+cd ..
+rm -r test
+
+
 rm -r "$suite-$arch"
diff --git a/mdk/m23helper/uploadEngine/tux05/ucs-upload b/mdk/m23helper/uploadEngine/tux05/ucs-upload
--- a/mdk/m23helper/uploadEngine/tux05/ucs-upload
+++ b/mdk/m23helper/uploadEngine/tux05/ucs-upload
@@ -10,13 +10,20 @@ debdir='aktuelles-m23Deb'
 rm -r $debdir 2> /dev/null
 mkdir $debdir
 cd $debdir
+
+if [ ! -f ../m23-Pakete-fuer-ucs.tar.gz ]
+then
+	echo "../m23-Pakete-fuer-ucs.tar.gz is MISSING!"
+	exit 1
+fi
+
 m23DebFile=$(tar xfvz ../m23-Pakete-fuer-ucs.tar.gz --wildcards --no-anchored m23_*.deb)
 m23Deb="$(pwd)/$m23DebFile"
 cd ..
 
 
-#for ucsVer in 4.3 4.2 4.1
-for ucsVer in 4.3
+for ucsVer in 4.3 4.4
+#for ucsVer in 4.3
 do
 	univention-selfservice upload $ucsVer/m23 m23-Pakete-fuer-ucs.tar.gz
 
@@ -25,6 +32,10 @@ do
 	neuDeb=$(./debAddVersionSuffix $m23Deb "ucs$debVer")
 	univention-selfservice upload $ucsVer/m23 $neuDeb
 	
+	unmaintainedTar="$(ls ucs-$ucsVer-unmaintained-m23*.tar.gz | sort -n | tail -1)"
+
+	univention-selfservice upload $ucsVer/m23 "$unmaintainedTar"
+
 	if [ $debVer -gt 42 ]
 	then
 		univention-selfservice upload $ucsVer/m23 m23-ucs-extra_18.2-101114_all.deb
