mdk-devel-backup from 2019-05-04 19:05

diff --git a/mdk/client/extraRFS/linuxrc b/mdk/client/extraRFS/linuxrc
--- a/mdk/client/extraRFS/linuxrc
+++ b/mdk/client/extraRFS/linuxrc
@@ -1,5 +1,38 @@
 #!/bin/sh
 
+# ---------------------
+# Define variable WITH_HAVEGED iff you like to
+# use random source haveged.
+#   WITH_HAVEGED="defined"
+# Otherwise, define the variable as empty string.
+#   WITH_HAVEGED=""
+
+#WITH_HAVEGED=""
+WITH_HAVEGED="defined"
+
+#For ANSI colors
+# eg. described in https://www.linuxjournal.com/article/8603
+ESC=""
+NORMAL="${ESC}[0;39m"
+BLACK="${ESC}[1;30m"
+# RED: Failure or error message
+RED="${ESC}[1;31m"
+# GREEN: Success message
+GREEN="${ESC}[1;32m"
+# YELLOW: Descriptions
+YELLOW="${ESC}[1;33m"
+# BLUE: System messages
+BLUE="${ESC}[1;34m"
+BLUE_EMPHASIZED="${ESC}[5;34m"
+# MAGENTA: Found devices or drivers
+MAGENTA="${ESC}[1;35m"
+# CYAN: Questions
+CYAN="${ESC}[1;36m"
+# BOLD WHITE: Hint
+WHITE="${ESC}[1;37m"
+
+echo "${BLUE}Starting linuxrc${NORMAL}"
+
 #For UEFI
 mount -o remount,rw /dev/ram0 /
 
@@ -13,7 +46,7 @@ touch /var/run/utmp
 
 for i in $( seq 0 9 )
 do
-	ifconfig eth$i 1.1.1.$i
+	ifconfig eth$i 1.1.1.$i > /dev/null 2>&1
 done
 
 #Show the MAC adress(es)
@@ -27,19 +60,31 @@ ln -s /bin/dhclient-script /sbin/dhclient-script
 
 #Configure via DHCP
 dhclient-script
-dhclient
+
+# FABR: mute error channel of dhclient
+# The binary makes a call to chmod with some option that is not supported by
+# chmod code built into busybox.
+
+dhclient > /dev/null 2>&1
 
 #Stop dhclient to make sure that the IP configuration will not be changed during installation
 for dhClientPID in `ps | grep dhclient | tr -s [:blank:] | cut -d' ' -f2`
 do
-	kill -9 $dhClientPID
+	kill -9 $dhClientPID > /dev/null 2>&1
 done
 
-killall -9 dhclient
+killall -9 dhclient  > /dev/null 2>&1
 
+if [ -z $WITH_HAVEGED ]
+then
 #Configure random as non blocking random
+	mv /dev/random /dev/random-blocks
+	ln -s /dev/urandom /dev/random
+else
+	# Prepare usage of haveged
 rm /dev/random
 mknod -m 444 /dev/random c 1 9
+fi
 
 for i in `seq 1 9`
 do
@@ -120,11 +165,19 @@ startDropbear()
 	mkdir -p /root/.ssh
 	chmod 700 /root/.ssh
 
-	wget -O - http://$server/packages/baseSys/authorized_keys >> /root/.ssh/authorized_keys
+	echo ""
+	echo "${MAGENTA}wget -T2 -qq -O - http://$server/packages/baseSys/authorized_keys${NORMAL}"
+	wget -T2 -qq -O - http://$server/packages/baseSys/authorized_keys >> /root/.ssh/authorized_keys
 
+	if [ -f /root/.ssh/authorized_keys ]; then
+		echo "${GREEN}INFO: Successfully copied authorized_keys from the m23 server${NORMAL}"
 	chmod 700 /root/.ssh/authorized_keys
 	chown root /root/.ssh/authorized_keys
 	chgrp root /root/.ssh/authorized_keys
+	else
+	  	echo "${RED}ERROR: unable to wget /root/.ssh/authorized_keys from m23 server${NORMAL}"
+	fi
+	echo ""
 	
 	mkdir -p /etc/dropbear
 
@@ -212,31 +265,84 @@ else
 	done
 fi
 
-
-
-echo "(Pseudo)Random number generator is warimg up..."
-echo "This may cause a dalay of a few minutes. Please be patient."
+#----------------------
+# Debug
+#----------------------
+echo "${GREEN}"
+echo "DEBUG INFO:"
+echo "Client/Server parameters:"
+echo "server=$server"
+echo "m23Client=$m23Client"
+echo "${NORMAL}"
 
 if [ -z $server ]
 then
 	showNetworkDialog
 fi
 
-haveged
+#--------------------
+# Use alternative random source: haveged
+# 
 
+if [ ! -z $WITH_HAVEGED ]
+then
+haveged
+fi
+
+echo ""
+echo "${CYAN}"   
+echo "(Pseudo-)Random number generator is warming up..."
+echo "This may cause a delay of several minutes. Please be patient."
+echo ""
+echo "You may speed-up the initialization process if you press"
+echo "the SHIFT-key on the client's keyboard until you see the message"
+echo "${WHITE}     random: crng init done${CYAN}"
+echo "${NORMAL}"
+
+#--------------------
+# Activate ssh server
+
+startDropbear
+
+#------------------------------------------------
 #Try to download the first job and debug commands
-wget --no-check-certificate -d -T600 -t2 https://$server/work.php$m23Client -O work.php -o work.php.log
-wget --no-check-certificate -d -T600 -t2 https://$server/debugScreen.php$m23Client -O debug.sh -o debug.sh.log
+#--
+# Note:
+# If we download pages via SSL, we do not check the SSL certicicate of the server.
+# Option: --no-check-certificate
+#
+# CAVEAT: 
+# Using SSL requires an initialized random number generator in the kernel.
+# Creating some entropy via keyboard activity shortens the waiting time.
+
+# Download debug commands
+echo "${MAGENTA}wget -T600 -t2 -qq http://$server/debugScreen.php$m23Client -O debug.sh${NORMAL}"
+wget -T600 -t2 -qq http://$server/debugScreen.php$m23Client -O debug.sh
+
+# Download the first job
+# Use SSL to make sure that the random generator is initialized
+# for later phases of the auto-installation.
+echo "${MAGENTA}wget -T600 -t2 -qq --no-check-certificate https://$server/work.php$m23Client -O work.php${NORMAL}"
+wget -T600 -t2 -qq --no-check-certificate https://$server/work.php$m23Client -O work.php
+#echo "${MAGENTA}wget -T600 -t2 -qq --no-check-certificate https://$server/work.php$m23Client -O work.php${NORMAL}"
+#wget -T600 -t2 -qq http://$server/work.php$m23Client -O work.php
 
 #########DEBUG##########
 
-# Check, if the work.php contains the required "bin/bash" line
-if [ $(grep -c 'bin/bash' work.php) -eq 0 ]
+# Check, if the work.php contains the required shebang in the first 5 lines: "#!/bin/bash"
+if [ $(head -5 work.php 2>/dev/null | grep -c '/bin/bash') -eq 0 ]
 then
-	# Ask for settings and try to download again
-	showNetworkDialog
-	wget --no-check-certificate -T600 -t0 https://$server/work.php$m23Client -O work.php
-	wget --no-check-certificate -T600 -t0 https://$server/debugScreen.php$m23Client -O debug.sh
+	echo ""
+	echo "${RED}FATAL ERROR${NORMAL}"
+	echo "${RED}work.php does not contain expected shebang in line 1${NORMAL}"
+	echo ""
+	exit 1
+else
+	echo ""
+	echo "${GREEN}work.php contains expected shebang in line 1${NORMAL}"
+        sleep 5
+#	echo "EXIT DEBUG"
+#	exit 0
 fi
 
 startDropbear
@@ -248,6 +354,6 @@ chmod +x debug.sh
 # Make work.php executable
 chmod +x work.php
 
-# Run work.php in screnn
+# Run work.php in screen
 export SCREENRC="/etc/screenrc"
 screen -mS m23install ./work.php
